# Generated by Django 3.1.9 on 2021-12-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='last_shared_on',
            field=models.CharField(choices=[(1, 'facebook'), (2, 'twitter'), (3, 'reddit')], default='', max_length=1),
        ),
    ]
