# Generated by Django 3.2.10 on 2022-01-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220109_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='launch_date',
            field=models.DateField(null=True),
        ),
    ]
