# Generated by Django 3.2.10 on 2022-01-10 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0010_alter_articles_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='unique_visitors',
            field=models.ManyToManyField(related_name='article_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
